## Trabalho Final de Disciplica - Introdução a Processamento de Dados

#### Turma: Engenharia de Dados - Turma 02
#### Nome Completo:Dante de Oliveira Dantas
#### Matrícula:2518583

#### ---------------------------------------------------------------------------------------------------------------------------------------------

### Instruções:
##### O objetivo deste trabalho é processar os dados do Enem 2023, salvar os resultados em um banco de dados PostgreSQL, consultar esses dados utilizando Pandas (Python) e responder a um conjunto de perguntas analíticas.
#### Passos para Execução

1. Download dos Dados
Baixe o arquivo de microdados do Enem 2023 no link abaixo:

[Microdados Enem 2023 - INEP](https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/enem)

Utilize o dicionário de dados disponível no site para entender o significado de cada coluna.

2. Processamento dos Dados
Realize o tratamento necessário nos dados, como:

Limpeza (remoção de valores ausentes ou inconsistentes)

Seleção de colunas relevantes

Conversão de tipos de dados, se necessário

Descreva brevemente os principais tratamentos realizados.

3. Armazenamento no Banco de Dados
Salve os dados tratados em um banco de dados PostgreSQL.

Documente:

O nome do banco de dados e das tabelas utilizadas

O método/ferramenta utilizada para realizar a carga (por exemplo: script Python, Pandas, PgAdmin, etc.)

4. Consulta e Análise com Pandas
Utilize a biblioteca Pandas (Python) para consultar os dados diretamente do banco de dados.

Responda às perguntas analíticas fornecidas utilizando funções do Pandas.

Apresente as respostas juntamente com o código utilizado para obtê-las.

## =====================================================

#### Import csv

In [ ]:
import pandas as pd

df = pd.read_csv('MICRODADOS_ENEM_2023.csv',encoding='latin-1', sep=';')

df.head()

df.isnull().sum()

AttributeError: 'function' object has no attribute 'sum'

### Tratamento dos dados

Professor, eu fiquei na duvida se era para eu colocar as colunas relevantes para fazer as questoes ou se era as colunas relevantes q eu achava,  na duvida coloquei umas extras que nao precisaria para fazer as consultas das questoes que o senhor pediu.

Primeira coisa que eu fiz, foi pegar apenas as colunas que achei mais interessante para tratar os dados, após isso, fui no documento do dicionario do enem e fiz variaveis que iam receber os dicionarios, para ficar mais visual a tabela e não ficar so 0,1,2 ou letras aleátorias.Eu vi que algumas colunas tinham o mesmo codigo para determinada situação, por exemplo o Q001 e Q002, era sobre escolaridade dos pais, para facilitar, botei os em uma lista e fiz um for com um map, que assim, poderia usar um codigo para ambas as colunas.

Logo em seguida, usei um df.isnull.sum() e percebi que apenas status da redação tinha valores null(Pelo menos das colunas que eu escolhi), ai para tratar, substitui os NaN para ficar como Situação não informada. Ai, depois  mudei o nome de todas as colunas, para nomes que eu achei mais interessantes e que ficassem mais fáceis de entender ao ler.

Sobre as notas, percebi que faltas nas provas geravam valores NaN nas colunas de nota. Para não afetar cálculos como médias e manter a integridade dos dados numéricos, optei por criar colunas extras de exibição, onde substituo os NaN por "Faltou". Assim, uso as colunas originais para cálculos e as extras para exibição.

In [ ]:
import pandas as pd
import numpy as np

colunas_usadas = [
    "TP_FAIXA_ETARIA",
    "TP_SEXO",
    "TP_COR_RACA",
    "TP_NACIONALIDADE",
    "TP_ST_CONCLUSAO",
    "TP_ESCOLA",
    "IN_TREINEIRO",
    "TP_PRESENCA_CN",
    "TP_PRESENCA_CH",
    "TP_PRESENCA_LC",
    "TP_PRESENCA_MT",
    "TP_STATUS_REDACAO",
    "NU_NOTA_MT", 
    "NU_NOTA_REDACAO",
    "Q001",
    "Q002",
    "Q006",
]

mapeamento_raca = {
    0: "Não declarada",
    1: "Branca",
    2: "Preta",
    3: "Parda",
    4: "Amarela",
    5: "Indígena",
}

mapeamento_nacionalidade = {
    0: "Não informado",
    1: "Brasileiro(a)",
    2: "Brasileiro(a) Naturalizado(a)",
    3: "Estrangeiro(a)",
    4: "Brasileiro(a) Nato(a), nascido(a) no exterior",
}

mapeamento_Situaçao_de_Conclusao = {
    1: "Já concluí o Ensino Médio",
    2: "Estou cursando e concluirei o Ensino Médio em 2023",
    3: "Estou cursando e concluirei o Ensino Médio após 2023",
    4: "Não concluí e não estou cursando o Ensino Médio",
}

mapeamento_Faixa_etaria = {
    1: "Menor de 17 anos",
    2: "17 anos",
    3: "18 anos",
    4: "19 anos",
    5: "20 anos",
    6: "21 anos",
    7: "22 anos",
    8: "23 anos",
    9: "24 anos",
    10: "25 anos",
    11: "Entre 26 e 30 anos",
    12: "Entre 31 e 35 anos",
    13: "Entre 36 e 40 anos",
    14: "Entre 41 e 45 anos",
    15: "Entre 46 e 50 anos",
    16: "entre 51 e 55 anos",
    17: "Entre 56 e 60 anos",
    18: "Entre 61 e 65 anos",
    19: "Entre 66 e 70 anos",
    20: "Maior de 70 anos",
}

coluna_presenca = ["Presença CN", "Presença CH", "Presença LC", "Presença MT"]
mapeamento_tipo_escola = {
    1: "Nao respondeu",
    2: "Pública",
    3: "Privada",
}

mapeamento_treineiro = {
    1: "Sim",
    0: "Não",
}

mapeamento_presenca = {
    0: "Faltou a prova",
    1: "Presente na prova",
    2: "Eliminado na prova",
}

coluna_pais = ["Nivel academico do pai", "Nivel academico da mãe"]
mapeamento_academico_pais = {
    "A": "Nunca Estudou",
    "B": "NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAMENTAL",
    "C": "COMPLETOU A 4 SERIE/5 ANO, MAS NAO COMPLETOU A 8 SERIE/9 ANO DO ENSINO FUNDAMENTAL",
    "D": "Completou a 8ª série/9º ano do Ensino Fundamental, mas não completou o Ensino Médio.",
    "E": "Completou o Ensino Médio, mas não completou a Faculdade.",
    "F": "Completou a Faculdade, mas não completou a Pós-graduação.",
    "G": "Completou a Pós-graduação.",
    "H": " Não sei.",
}

mapeamento_renda_familia = {
    "A": "NENHUMA RENDA",
    "B": "Até R$ 1.320,00",
    "C": "De R$ 1.320,01 até R$ 1.980,00.",
    "D": "De R$ 1.980,01 até R$ 2.640,00.",
    "E": "De R$ 2.640,01 até R$ 3.300,00.",
    "F": "De R$ 3.300,01 até R$ 3.960,00.",
    "G": "De R$ 3.960,01 até R$ 5.280,00.",
    "H": "De R$ 5.280,01 até R$ 6.600,00.",
    "I": "De R$ 6.600,01 até R$ 7.920,00.",
    "J": "De R$ 7.920,01 até R$ 9240,00.",
    "K": "De R$ 9.240,01 até R$ 10.560,00.",
    "L": "De R$ 10.560,01 até R$ 11.880,00.",
    "M": "De R$ 11.880,01 até R$ 13.200,00.",
    "N": "De R$ 13.200,01 até R$ 15.840,00.",
    "O": "De R$ 15.840,01 até R$19.800,00.",
    "P": "De R$ 19.800,01 até R$ 26.400,00.",
    "Q": "Acima de R$ 26.400,00.",
}

mapeamento_status_redacao = {
    1: "Sem problemas",
    2: "Anulada",
    3: "Cópia Texto Motivador",
    4: "Em Branco",
    6: "Fuga ao Tema",
    7: "Não atendimento ao tipo textual",
    8: "Texto insuficiente",
    9: "Parte desconectada",
}

In [ ]:
df = pd.read_csv(
    "MICRODADOS_ENEM_2023.csv", sep=";", usecols=colunas_usadas, encoding="latin-1"
)

df = df.rename(
    columns={
        "TP_FAIXA_ETARIA": "Faixa Etária",
        "TP_SEXO": "Sexo",
        "TP_COR_RACA": "Cor ou Raça",
        "TP_NACIONALIDADE": "Nacionalidade",
        "TP_ST_CONCLUSAO": "Situação de Conclusão",
        "TP_ESCOLA": "Tipo de Escola",
        "IN_TREINEIRO": "Treineiro",
        "TP_PRESENCA_CN": "Presença CN",
        "TP_PRESENCA_CH": "Presença CH",
        "TP_PRESENCA_LC": "Presença LC",
        "TP_PRESENCA_MT": "Presença MT",
        "TP_STATUS_REDACAO": "Status Redação",
        "Q001": "Nivel academico do pai",
        "Q002": "Nivel academico da mãe",
        "Q006": "Renda mensal da familia",
        "NU_NOTA_MT" : "Nota matematica", 
        "NU_NOTA_REDACAO" : "Nota Redação",
    }
)

df["Status Redação"] = df["Status Redação"].map(mapeamento_status_redacao)
df["Status Redação"] = df["Status Redação"].fillna("Situação não informada")

df["Nota Redação"] = pd.to_numeric(df["Nota Redação"], errors="coerce")
df["Nota matematica"] = pd.to_numeric(df["Nota matematica"], errors="coerce")
df["Nota Redação (exibição)"] = df["Nota Redação"].fillna("Faltou")
df["Nota matematica (exibição)"] = df["Nota matematica"].fillna("Faltou")


df["Cor ou Raça"] = df["Cor ou Raça"].map(mapeamento_raca)
df["Nacionalidade"] = df["Nacionalidade"].map(mapeamento_nacionalidade)
df["Situação de Conclusão"] = df["Situação de Conclusão"].map(
    mapeamento_Situaçao_de_Conclusao
)
df["Faixa Etária"] = df["Faixa Etária"].map(mapeamento_Faixa_etaria)
df["Tipo de Escola"] = df["Tipo de Escola"].map(mapeamento_tipo_escola)
df["Treineiro"] = df["Treineiro"].map(mapeamento_treineiro)
for coluna in coluna_presenca:
    df[coluna] = df[coluna].map(mapeamento_presenca)
for coluna in coluna_pais:
    df[coluna] = df[coluna].map(mapeamento_academico_pais)
df["Renda mensal da familia"] = df["Renda mensal da familia"].map(
    mapeamento_renda_familia
)

df.head()

,Faixa Etária,Sexo,Cor ou Raça,Nacionalidade,Situação de Conclusão,Tipo de Escola,Treineiro,Presença CN,Presença CH,Presença LC,Presença MT,Nota matematica,Status Redação,Nota Redação,Nivel academico do pai,Nivel academico da mãe,Renda mensal da familia,Nota Redação (exibição),Nota matematica (exibição),Renda mensal da familia (exibição)
0,Entre 41 e 45 anos,M,Branca,Brasileiro(a),Já concluí o Ensino Médio,Nao respondeu,Não,Faltou a prova,Faltou a prova,Faltou a prova,Faltou a prova,NaN,Situação não informada,NaN,Nunca Estudou,"Completou a Faculdade, mas não completou a Pós...","De R$ 3.300,01 até R$ 3.960,00.",Faltou,Faltou,"De R$ 3.300,01 até R$ 3.960,00."
1,Entre 31 e 35 anos,M,Branca,Não informado,Já concluí o Ensino Médio,Nao respondeu,Não,Faltou a prova,Faltou a prova,Faltou a prova,Faltou a prova,NaN,Situação não informada,NaN,"Completou a Faculdade, mas não completou a Pós...","Completou o Ensino Médio, mas não completou a ...","De R$ 5.280,01 até R$ 6.600,00.",Faltou,Faltou,"De R$ 5.280,01 até R$ 6.600,00."
2,21 anos,F,Branca,Brasileiro(a),Já concluí o Ensino Médio,Nao respondeu,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,363.2,Sem problemas,700.0,Não sei.,"Completou o Ensino Médio, mas não completou a ...","De R$ 1.320,01 até R$ 1.980,00.",700.0,363.2,"De R$ 1.320,01 até R$ 1.980,00."
3,17 anos,F,Parda,Brasileiro(a),Estou cursando e concluirei o Ensino Médio em ...,Pública,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,466.7,Sem problemas,880.0,Completou a 8ª série/9º ano do Ensino Fundamen...,Completou a 8ª série/9º ano do Ensino Fundamen...,"De R$ 1.320,01 até R$ 1.980,00.",880.0,466.7,"De R$ 1.320,01 até R$ 1.980,00."
4,18 anos,F,Parda,Brasileiro(a),Estou cursando e concluirei o Ensino Médio em ...,Pública,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,338.3,Sem problemas,560.0,NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAM...,NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAM...,"Até R$ 1.320,00",560.0,338.3,"Até R$ 1.320,00"

### Insert no Banco de Dados

In [ ]:
from sqlalchemy import create_engine

usuario = "postgres"
senha = "root"
host = "localhost"
porta = "5432"
banco = "Unifor"

engine = create_engine(
    f"postgresql+psycopg2://{usuario}:{senha}@{host}:{porta}/{banco}"
)

df.to_sql("dados_enem_2023", engine, if_exists="replace", index=False)

955

       Colunas ultilidas
        "TP_FAIXA_ETARIA": "Faixa Etária",
        "TP_SEXO": "Sexo",
        "TP_COR_RACA": "Cor ou Raça",
        "TP_NACIONALIDADE": "Nacionalidade",
        "TP_ST_CONCLUSAO": "Situação de Conclusão",
        "TP_ESCOLA": "Tipo de Escola",
        "IN_TREINEIRO": "Treineiro",
        "TP_PRESENCA_CN": "Presença CN",
        "TP_PRESENCA_CH": "Presença CH",
        "TP_PRESENCA_LC": "Presença LC",
        "TP_PRESENCA_MT": "Presença MT",
        "TP_STATUS_REDACAO": "Status Redação",
        "Q001": "Nivel academico do pai",
        "Q002": "Nivel academico da mãe",
        "Q006": "Renda mensal da familia",

        Usei o banco de dados PostgresSQL
        Ferramenta ultilizada para fazer a carga o banco foi o PANDAS

### Recuperação dos dados usando Pandas

In [ ]:
df_db = pd.read_sql("SELECT * FROM dados_enem_2023",engine)

In [ ]:
df_db.head()

,Faixa Etária,Sexo,Cor ou Raça,Nacionalidade,Situação de Conclusão,Tipo de Escola,Treineiro,Presença CN,Presença CH,Presença LC,Presença MT,Nota matematica,Status Redação,Nota Redação,Nivel academico do pai,Nivel academico da mãe,Renda mensal da familia,Nota Redação (exibição),Nota matematica (exibição),Renda mensal da familia (exibição)
0,Entre 41 e 45 anos,M,Branca,Brasileiro(a),Já concluí o Ensino Médio,Nao respondeu,Não,Faltou a prova,Faltou a prova,Faltou a prova,Faltou a prova,NaN,Situação não informada,NaN,Nunca Estudou,"Completou a Faculdade, mas não completou a Pós...","De R$ 3.300,01 até R$ 3.960,00.",Faltou,Faltou,"De R$ 3.300,01 até R$ 3.960,00."
1,Entre 31 e 35 anos,M,Branca,Não informado,Já concluí o Ensino Médio,Nao respondeu,Não,Faltou a prova,Faltou a prova,Faltou a prova,Faltou a prova,NaN,Situação não informada,NaN,"Completou a Faculdade, mas não completou a Pós...","Completou o Ensino Médio, mas não completou a ...","De R$ 5.280,01 até R$ 6.600,00.",Faltou,Faltou,"De R$ 5.280,01 até R$ 6.600,00."
2,21 anos,F,Branca,Brasileiro(a),Já concluí o Ensino Médio,Nao respondeu,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,363.2,Sem problemas,700.0,Não sei.,"Completou o Ensino Médio, mas não completou a ...","De R$ 1.320,01 até R$ 1.980,00.",700.0,363.2,"De R$ 1.320,01 até R$ 1.980,00."
3,17 anos,F,Parda,Brasileiro(a),Estou cursando e concluirei o Ensino Médio em ...,Pública,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,466.7,Sem problemas,880.0,Completou a 8ª série/9º ano do Ensino Fundamen...,Completou a 8ª série/9º ano do Ensino Fundamen...,"De R$ 1.320,01 até R$ 1.980,00.",880.0,466.7,"De R$ 1.320,01 até R$ 1.980,00."
4,18 anos,F,Parda,Brasileiro(a),Estou cursando e concluirei o Ensino Médio em ...,Pública,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,338.3,Sem problemas,560.0,NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAM...,NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAM...,"Até R$ 1.320,00",560.0,338.3,"Até R$ 1.320,00"

In [ ]:
df_db.isnull().sum()

### Perguntas:

#### 1 - Qual o percentual de faltas dos cantidatos na disciplina de Matemática e Redação?

In [ ]:
total_mt = len(df)
faltas_mt = (df["Presença MT"] == "Faltou a prova").sum()
percentual_faltas_mt = (faltas_mt / total_mt) * 100

total_redacao = len(df)
faltas_redacao = (df["Status Redação"] == "Situação não informada").sum()
percentual_faltas_redacao = (faltas_redacao / total_redacao) * 100

In [ ]:
print(f"Faltas em Matemática: {percentual_faltas_mt:.2f}%")
print(f"Faltas em Redação: {percentual_faltas_redacao:.2f}%")

Faltas em Matemática: 31.50%
Faltas em Redação: 28.25%

#### 2 - Se formos olhar para a distribuição das idades dos alunos, como estaria a distribuição dos alunos por faixas etárias?

In [ ]:
distribuicao_idade = df["Faixa Etária"].value_counts().sort_index()
print(distribuicao_idade)

Faixa Etária
17 anos               753800
18 anos               905047
19 anos               431592
20 anos               267383
21 anos               183401
22 anos               137884
23 anos               111813
24 anos                91359
25 anos                73127
Entre 26 e 30 anos    246292
Entre 31 e 35 anos    133381
Entre 36 e 40 anos     96927
Entre 41 e 45 anos     67135
Entre 46 e 50 anos     40791
Entre 56 e 60 anos     13439
Entre 61 e 65 anos      5503
Entre 66 e 70 anos      2161
Maior de 70 anos         867
Menor de 17 anos      347434
entre 51 e 55 anos     24619
Name: count, dtype: int64

### 3 - Quem tem as melhores notas em matemática e redação, candidatos do sexo masculino ou feminino?

In [ ]:
media_por_sexo_db = (
    df_db.groupby("Sexo")[["Nota matematica", "Nota Redação"]].mean().round(2)
)

print(media_por_sexo_db)

      Nota matematica  Nota Redação
Sexo
F              516.84        634.93
M              560.80        590.50

### 4 - Há alguma influência no tipo da escola (publica e privada) nas notas de matemática e redação?

In [ ]:
df_filtrado = df_db[
    df_db["Tipo de Escola"].isin(["Pública", "Privada", "Nao respondeu"])
]

media_por_escola = (
    df_filtrado.groupby("Tipo de Escola")[["Nota matematica", "Nota Redação"]]
    .mean()
    .round(2)
)

print(media_por_escola)

                Nota matematica  Nota Redação
Tipo de Escola
Nao respondeu            535.91        616.19
Privada                  630.77        762.63
Pública                  503.98        583.75

### 5 - Qual a influência da escolaridade do Pai nas notas de Matemática e Redação?

In [ ]:
media_por_escolaridade_pai = (
    df_db.groupby("Nivel academico do pai")[["Nota matematica", "Nota Redação"]]
    .mean()
    .round(2)
)

print(media_por_escolaridade_pai)

                                                    Nota matematica  \
Nivel academico do pai
 Não sei.                                                    496.69
COMPLETOU A 4 SERIE/5 ANO, MAS NAO COMPLETOU A ...           506.02
Completou a 8ª série/9º ano do Ensino Fundament...           517.76
Completou a Faculdade, mas não completou a Pós-...           613.12
Completou a Pós-graduação.                                   632.72
Completou o Ensino Médio, mas não completou a F...           545.06
NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAME...           483.04
Nunca Estudou                                                454.95

                                                    Nota Redação
Nivel academico do pai
 Não sei.                                                 559.59
COMPLETOU A 4 SERIE/5 ANO, MAS NAO COMPLETOU A ...        588.55
Completou a 8ª série/9º ano do Ensino Fundament...        603.14
Completou a Faculdade, mas não completou a Pós-...        709.34
Completou a Pós-graduação.                                732.04
Completou o Ensino Médio, mas não completou a F...        636.84
NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAME...        558.23
Nunca Estudou                                             512.77

### 6 - Qual a influência da escolaridade do Mãe nas notas de Matemática e Redação?

In [ ]:
media_por_escolaridade_mae = (
    df_db.groupby("Nivel academico da mãe")[["Nota matematica", "Nota Redação"]]
    .mean()
    .round(2)
)

print(media_por_escolaridade_mae)

                                                    Nota matematica  \
Nivel academico da mãe
 Não sei.                                                    483.02
COMPLETOU A 4 SERIE/5 ANO, MAS NAO COMPLETOU A ...           491.28
Completou a 8ª série/9º ano do Ensino Fundament...           502.40
Completou a Faculdade, mas não completou a Pós-...           593.89
Completou a Pós-graduação.                                   608.87
Completou o Ensino Médio, mas não completou a F...           532.18
NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAME...           472.44
Nunca Estudou                                                444.55

                                                    Nota Redação
Nivel academico da mãe
 Não sei.                                                 520.35
COMPLETOU A 4 SERIE/5 ANO, MAS NAO COMPLETOU A ...        566.38
Completou a 8ª série/9º ano do Ensino Fundament...        582.33
Completou a Faculdade, mas não completou a Pós-...        690.55
Completou a Pós-graduação.                                710.49
Completou o Ensino Médio, mas não completou a F...        621.07
NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAME...        539.99
Nunca Estudou                                             488.17

### 7 - Qual a influência da renda do Pai e da Mãe nas notas de Matemática e Redação?

In [ ]:
media_por_renda = (
    df_db.groupby("Renda mensal da familia")[["Nota matematica", "Nota Redação"]]
    .mean()
    .round(2)
)

print(media_por_renda)

                                   Nota matematica  Nota Redação
Renda mensal da familia
Acima de R$ 26.400,00.                      685.82        769.83
Até R$ 1.320,00                             476.60        559.03
De R$ 1.320,01 até R$ 1.980,00.             510.25        592.04
De R$ 1.980,01 até R$ 2.640,00.             530.70        613.94
De R$ 10.560,01 até R$ 11.880,00.           640.10        735.15
De R$ 11.880,01 até R$ 13.200,00.           649.71        744.27
De R$ 13.200,01 até R$ 15.840,00.           654.03        749.56
De R$ 15.840,01 até R$19.800,00.            663.02        756.19
De R$ 19.800,01 até R$ 26.400,00.           674.20        765.86
De R$ 3.300,01 até R$ 3.960,00.             568.17        654.04
De R$ 3.960,01 até R$ 5.280,00.             584.29        674.40
De R$ 5.280,01 até R$ 6.600,00.             602.17        693.65
De R$ 6.600,01 até R$ 7.920,00.             613.41        708.95
De R$ 7.920,01 até R$ 9240,00.              624.44        720.68
De R$ 9.240,01 até R$ 10.560,00.            632.80        728.75
NENHUMA RENDA                               454.69        521.43

In [ ]:
df[df["Renda mensal da familia"].isnull()]

,Faixa Etária,Sexo,Cor ou Raça,Nacionalidade,Situação de Conclusão,Tipo de Escola,Treineiro,Presença CN,Presença CH,Presença LC,Presença MT,Nota matematica,Status Redação,Nota Redação,Nivel academico do pai,Nivel academico da mãe,Renda mensal da familia,Nota Redação (exibição),Nota matematica (exibição),Renda mensal da familia (exibição)
23,20 anos,F,Branca,Brasileiro(a),Já concluí o Ensino Médio,Nao respondeu,Não,Faltou a prova,Faltou a prova,Faltou a prova,Faltou a prova,NaN,Situação não informada,NaN,"COMPLETOU A 4 SERIE/5 ANO, MAS NAO COMPLETOU A...",NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAM...,NaN,Faltou,Faltou,Não informado
24,18 anos,F,Branca,Brasileiro(a),Já concluí o Ensino Médio,Nao respondeu,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,575.3,Sem problemas,880.0,"Completou o Ensino Médio, mas não completou a ...",Completou a 8ª série/9º ano do Ensino Fundamen...,NaN,880.0,575.3,Não informado
36,19 anos,F,Parda,Brasileiro(a),Já concluí o Ensino Médio,Nao respondeu,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,596.8,Sem problemas,940.0,"Completou a Faculdade, mas não completou a Pós...",Completou a Pós-graduação.,NaN,940.0,596.8,Não informado
43,20 anos,F,Branca,Brasileiro(a),Já concluí o Ensino Médio,Nao respondeu,Não,Faltou a prova,Presente na prova,Presente na prova,Faltou a prova,NaN,Sem problemas,540.0,Não sei.,"Completou o Ensino Médio, mas não completou a ...",NaN,540.0,Faltou,Não informado
58,19 anos,F,Parda,Brasileiro(a) Naturalizado(a),Já concluí o Ensino Médio,Nao respondeu,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,424.6,Sem problemas,500.0,Não sei.,"Completou o Ensino Médio, mas não completou a ...",NaN,500.0,424.6,Não informado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3933929,19 anos,M,Preta,Brasileiro(a),Já concluí o Ensino Médio,Nao respondeu,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,643.7,Sem problemas,900.0,Não sei.,"Completou a Faculdade, mas não completou a Pós...",NaN,900.0,643.7,Não informado
3933931,19 anos,F,Branca,Brasileiro(a),Já concluí o Ensino Médio,Nao respondeu,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,568.4,Sem problemas,820.0,Completou a 8ª série/9º ano do Ensino Fundamen...,NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAM...,NaN,820.0,568.4,Não informado
3933934,18 anos,M,Parda,Brasileiro(a),Estou cursando e concluirei o Ensino Médio em ...,Pública,Não,Faltou a prova,Faltou a prova,Faltou a prova,Faltou a prova,NaN,Situação não informada,NaN,"Completou o Ensino Médio, mas não completou a ...","Completou o Ensino Médio, mas não completou a ...",NaN,Faltou,Faltou,Não informado
3933938,19 anos,F,Branca,Brasileiro(a),Já concluí o Ensino Médio,Nao respondeu,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,450.8,Sem problemas,600.0,"Completou o Ensino Médio, mas não completou a ...",NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAM...,NaN,600.0,450.8,Não informado
3933939,Entre 46 e 50 anos,M,Branca,Brasileiro(a),Já concluí o Ensino Médio,Nao respondeu,Não,Presente na prova,Presente na prova,Presente na prova,Presente na prova,521.6,Sem problemas,560.0,Nunca Estudou,NAO COMPLETOU A 4 SERIE/5 ANO DO ENSINO FUNDAM...,NaN,560.0,521.6,Não informado